### ISSUE TITLE
:magic_wand: [FEAT] Introduce Write to File support with path config

### ISSUE THREAD

**Issue by akashchouhan16** [akashchouhan16/nodeCache.js#51]
## Overview
- Adding support for writing to files using the existing path config.
> ![image](https://github.com/akashchouhan16/nodeCache.js/assets/56465610/2c890b32-0701-4488-95b6-223c1f85499c)

**TODO:**
- [ ] - Set Input path validations in place
- [ ] - Able to fallback to a pre-defined path: `rootdir/application.log.*`
- [ ] - Refactor code to comply with SOLID.
